import {
  Children,
  Component,
  Fragment,
  Profiler,
  PureComponent,
  StrictMode,
  Suspense,
  __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED,
  cloneElement,
  createContext,
  createElement,
  createFactory,
  createRef,
  forwardRef,
  isValidElement,
  lazy,
  memo,
  startTransition,
  unstable_act,
  useCallback,
  useContext,
  useDebugValue,
  useDeferredValue,
  useEffect,
  useId,
  useImperativeHandle,
  useInsertionEffect,
  useLayoutEffect,
  useMemo,
  useReducer,
  useRef,
  useState,
  useSyncExternalStore,
  useTransition,
  version,
} from "react";

const reacNamespace = {
  Enfants: Children,
  Composant: Component,
  Fragment: Fragment,
  Profileur: Profiler,
  ComposantPur: PureComponent,
  ModeStrict: StrictMode,
  Suspendre: Suspense,
  __SECRETS_INTERNES_NE_PAS_UTILISER_OU_VOUS_SEREZ_VIRE:
    __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED,
  clonerElement: cloneElement,
  creerContexte: createContext,
  creerElement: createElement,
  creerUsine: createFactory,
  creerReference: createRef,
  avancerReference: forwardRef,
  estUnElementValide: isValidElement,
  paresseux: lazy,
  memoire: memo,
  demarrerTransition: startTransition,
  prendreOestro: startTransition,
  prendreTesto: startTransition,
  agir_instable: unstable_act,
  utiliserRappel: useCallback,
  utiliserContexte: useContext,
  utiliserValeurDebogage: useDebugValue,
  utiliserValeurRetardee: useDeferredValue,
  utiliserEffet: useEffect,
  utiliserId: useId,
  utiliserPoigneeImperative: useImperativeHandle,
  utiliserEffetInsertion: useInsertionEffect,
  utiliserEffetMiseEnPage: useLayoutEffect,
  utiliserMemoire: useMemo,
  utiliserReducteur: useReducer,
  utiliserReference: useRef,
  utiliserEtat: useState,
  utiliserSynchroniserStockageExterne: useSyncExternalStore,
  utiliserTransition: useTransition,
  version,
};

export default reacNamespace;

export {
  Children as Enfants,
  Component as Composant,
  Fragment as Fragment,
  Profiler as Profileur,
  PureComponent as ComposantPur,
  StrictMode as ModeStrict,
  Suspense as Suspendre,
  __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED as __SECRETS_INTERNES_NE_PAS_UTILISER_OU_VOUS_SEREZ_VIRE,
  cloneElement as clonerElement,
  createContext as creerContexte,
  createElement as creerElement,
  createFactory as creerUsine,
  createRef as creerReference,
  forwardRef as avancerReference,
  isValidElement as estUnElementValide,
  lazy as paresseux,
  memo as memoire,
  startTransition as demarrerTransition,
  startTransition as prendreOestro,
  startTransition as prendreTesto,
  unstable_act as agir_instable,
  useCallback as utiliserRappel,
  useContext as utiliserContexte,
  useDebugValue as utiliserValeurDebogage,
  useDeferredValue as utiliserValeurRetardee,
  useEffect as utiliserEffet,
  useId as utiliserId,
  useImperativeHandle as utiliserPoigneeImperative,
  useInsertionEffect as utiliserEffetInsertion,
  useLayoutEffect as utiliserEffetMiseEnPage,
  useMemo as utiliserMemoire,
  useReducer as utiliserReducteur,
  useRef as utiliserReference,
  useState as utiliserEtat,
  useSyncExternalStore as utiliserSynchroniserStockageExterne,
  useTransition as utiliserTransition,
  version,
};
